/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_isure_audio_Speex */

#ifndef _Included_com_isure_audio_Speex
#define _Included_com_isure_audio_Speex
#ifdef __cplusplus
extern "C" {
#endif
#undef com_isure_audio_Speex_DEFAULT_COMPRESSION
#define com_isure_audio_Speex_DEFAULT_COMPRESSION 8L
/*
 * Class:     com_isure_audio_Speex
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_isure_audio_Speex_open
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_isure_audio_Speex
 * Method:    getFrameSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_isure_audio_Speex_getFrameSize
  (JNIEnv *, jclass);

/*
 * Class:     com_isure_audio_Speex
 * Method:    decode
 * Signature: ([B[SI)I
 */
JNIEXPORT jint JNICALL Java_com_isure_audio_Speex_decode
  (JNIEnv *, jclass, jbyteArray, jshortArray, jint);

/*
 * Class:     com_isure_audio_Speex
 * Method:    encode
 * Signature: ([SI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_isure_audio_Speex_encode
  (JNIEnv *, jclass, jshortArray, jint, jbyteArray, jint);

/*
 * Class:     com_isure_audio_Speex
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_isure_audio_Speex_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
